# Generated by Django 3.1.5 on 2021-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creater', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year_create', models.IntegerField(max_length=4)),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')])),
                ('color', models.SmallIntegerField(choices=[(1, 'Черный'), (2, 'Красный'), (3, 'Белый'), (4, 'Мокрый асфальт'), (5, 'Желтый')])),
            ],
        ),
    ]
