# Generated by Django 3.1.5 on 2021-01-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_filter', '0002_auto_20210123_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cars_photo/'),
        ),
    ]
