# Generated by Django 3.1.5 on 2021-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_filter', '0003_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('Механика', 'Механика'), ('Автомат', 'Автомат'), ('Робот', 'Робот')]),
        ),
    ]
