# Generated by Django 3.1.5 on 2021-01-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_filter', '0004_auto_20210126_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')]),
        ),
    ]
